### ISSUE TITLE
[BUG] Browser auto fill cause duplicate street values

### ISSUE THREAD

**Issue by Paulsky** [postcodeservice/postcode-magento2#53]
**To Reproduce**
1. Go to checkout
2. Fill in correct postcode and housenumber
3. TIG street field is automatically filled in. Example: 'Hoofdstraat'
4. TIG housenumber field is automatically filled in. Example: '8'
5. Click on TIG street field, if your browser has autofill/auto complete enabled, choose a option. Example 'hfdstraat'
6. TIG street field is changed
7. Street field is merged with old value and new value. After payment, the street field is something like: 'Hoofdstraat hfdstraat, 8 8'

**Expected result**
Or the autofill value is used (hfdstraat) or the autofill function is disabled on tig_street and tig_housenumber

**Actual result**
Both values are used and merged

**Workaround**
None, I'm wrting some JS for fixing this bug and other TIG bugs

- Magento version: [Magento 2.4.5]
- PHP version: [8.1]

**Comment by tig-jeffreybranderhorst** [comment]
Hi @Paulsky ,

We can not reproduce this at this moment, we used an autofilled address after the check. We did not see 2 values, the street field only had the autofilled address inside it, we cannot seem to reproduce it with these steps. Are you also using a one-step checkout in this case? 

Have a great day,
Jeffrey

**Comment by Paulsky** [comment]
Hello @tig-jeffreybranderhorst ,

Thank you for your reply. Yes, we also have OSC enabled in this case.

**Comment by tig-jeffreybranderhorst** [comment]
Hi @Paulsky ,

Then it could be the same reason I have given in #51 and #52.
There is a change in the future we will support the onestepcheckout.com extension.

Have a great day,
Jeffrey

**Comment by schldwcht** [comment]
Hi @Paulsky,
I wanted to inform you that, after careful consideration, we have decided not to support the OSC of OneStepCheckout.com at this time. Although we may revisit this decision in the future, we have decided to close this issue for the time being.
Best regards,
Joost
